name:                bitcoin-rate
version:             0.1.0.0
github:              "lwheng/bitcoin-rate"
license:             BSD3
author:              "Heng Low Wee"
maintainer:          "alpha116@gmail.com"
copyright:           "2020 Heng Low Wee"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A simple application to view Bitcoin rate from Coindesk
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lwheng/bitcoin-rate#readme>

dependencies:
- base >= 4.7 && < 5
- lens
- lens-aeson
- bytestring
- text
- http-conduit
- blaze-builder
- http-types
- utf8-string
- wai
- warp

library:
  source-dirs: src

executables:
  bitcoin-rate-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bitcoin-rate

tests:
  bitcoin-rate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - bitcoin-rate
